#!/usr/bin/env python3
"""Generates all 40 knowledge JSON files for the AI generation pipeline."""
import json, pathlib

BASE = pathlib.Path(__file__).parent.parent / "knowledge"

# ─── MBTI TYPES ──────────────────────────────────────────────────────────────
MBTI = {
"INTJ": {"type":"INTJ","name":"The Architect","work_style":"Independent, systematic and long-horizon. Work best when given a complex problem and autonomy to solve it. Prefer deep work over meetings. Strategy and architecture over execution details.","strengths":["Systems thinking","Long-range planning","Independent execution","Pattern recognition"],"energy_drains":["Micromanagement","Repetitive routine work","Political games without substance","Being asked to explain reasoning to unconvinced audiences repeatedly"],"environment_needs":["High autonomy","Intellectually rigorous colleagues","Clear goals with minimal process constraints","Work that has strategic impact"],"career_domains":["Software Architecture","Management Consulting","Research","Product Strategy","Data Science","Law","Investment Management","Entrepreneurship"],"decision_making":"Highly independent. Gather data extensively, then decide with conviction. Resistant to reversing decisions once made. Can appear stubborn — actually just high-conviction after deep analysis.","leadership_style":"Lead through vision and high standards. Set direction, delegate execution, intervene only when outcomes are at risk.","growth_edges":["Communicating rationale to others","Tolerance for imperfect team output","Recognising emotional dimensions of decisions"]},

"INTP": {"type":"INTP","name":"The Thinker","work_style":"Exploratory and concept-driven. Need intellectual freedom to question assumptions. Work best on novel problems with no established answer. Deep diver who loses track of time when genuinely engaged.","strengths":["Lateral thinking","Logical precision","Abstract pattern recognition","Theoretical model-building"],"energy_drains":["Administrative tasks","Rigid procedures","Emotionally charged environments","Being forced to commit before thorough analysis"],"environment_needs":["Intellectual freedom","Tolerance for unconventional approaches","Minimal bureaucracy","Problems at the frontier of a field"],"career_domains":["Research","Software Engineering","Data Science","Philosophy/Academia","Cryptography","Theoretical Physics","Systems Design","Technical Writing"],"decision_making":"Exhaustive analysis, sometimes to the point of paralysis. Need to acknowledge when 'good enough' data is available. Strong at identifying flaws in reasoning.","leadership_style":"Lead through ideas and analysis. Reluctant leaders who excel in technical advisory roles over formal management.","growth_edges":["Following through on implementation","Communicating ideas accessibly","Managing project closure"]},

"ENTJ": {"type":"ENTJ","name":"The Commander","work_style":"Strategic, decisive, execution-focused. Natural organiser who spots inefficiency and fixes it. Move fast, think big, delegate without hesitation. Thrive under pressure and in high-stakes environments.","strengths":["Strategic leadership","Decisive action","Talent development","Organisational design"],"energy_drains":["Incompetence in critical roles","Slow decision-making processes","Lack of direction or vision","Political avoidance of hard conversations"],"environment_needs":["Decision-making authority","High-calibre team","Ambitious goals","Clear metrics for success"],"career_domains":["C-Suite Leadership","Management Consulting","Entrepreneurship","Investment Banking","Operations","Corporate Law","Military Leadership","Private Equity"],"decision_making":"Fast, data-informed, and confident. Make decisions with 70-80% of ideal information rather than wait. Happy to revise if new data warrants it.","leadership_style":"Command and inspire simultaneously. High expectations, direct feedback, clear accountability. Develop top performers aggressively.","growth_edges":["Patience with different processing speeds","Emotional intelligence in high-stakes conversations","Delegation beyond task assignment"]},

"ENTP": {"type":"ENTP","name":"The Debater","work_style":"Idea generation, challenge-seeking, and opportunistic. Thrive in the early, ambiguous phase of any project. Excel at seeing possibilities others miss. Get bored with routine and need constant novelty.","strengths":["Creative problem-solving","Arguing multiple positions","Rapid prototype thinking","Connecting disparate domains"],"energy_drains":["Repetitive execution","Bureaucratic constraint","Detail-oriented work","Being told 'that's how we've always done it'"],"environment_needs":["Intellectual stimulation","Permission to challenge the status quo","Variety and novelty","Collaborative debate culture"],"career_domains":["Entrepreneurship","Venture Capital","Product Management","Consulting","Journalism","Marketing Strategy","Law","Innovation Labs"],"decision_making":"Quick to form opinions but genuinely open to counter-arguments. Enjoy debate as a means of reaching better decisions. Can be perceived as contrarian — actually just stress-testing ideas.","leadership_style":"Lead through energy and ideas. Excel at rallying people around bold new directions. Need strong operational partners to execute.","growth_edges":["Follow-through on commitments","Tolerance for necessary process","Distinguishing creative dissent from contrarianism"]},

"INFJ": {"type":"INFJ","name":"The Advocate","work_style":"Purpose-driven and people-aware. Need to believe in the work to sustain energy. Work best with deep focus on meaningful problems. Natural synthesiser who connects ideas across domains. Protective of time and attention.","strengths":["Deep empathy","Strategic insight","Vision articulation","One-to-one connection"],"energy_drains":["Work without clear purpose","Conflict without resolution","Bureaucracy for its own sake","Superficial relationships"],"environment_needs":["Meaningful mission","Autonomy and focus time","Small, trusted team","Clear ethical alignment"],"career_domains":["Organisational Development","UX Research","Counselling","Education","Healthcare","Social Impact","Product Strategy","Writing","Coaching"],"decision_making":"Led by intuition and values alignment. Gather information holistically, then feel into the right choice. May override logic if something 'feels wrong' — often correctly.","leadership_style":"Lead through inspiration and deep listening. Build consensus. Uncomfortable with authority for its own sake.","growth_edges":["Setting and holding boundaries","Taking action without full certainty","Distinguishing intuition from anxiety"]},

"INFP": {"type":"INFP","name":"The Mediator","work_style":"Values-first, creative, and individually driven. Need work to feel personally meaningful. Natural storyteller and empath. Work best with creative freedom and at their own pace. Highly productive when passion is engaged.","strengths":["Creative expression","Empathic insight","Deep values integration","Authentic communication"],"energy_drains":["Work that conflicts with values","Aggressive competitive environments","Forced social performance","Rigid metrics-only evaluation"],"environment_needs":["Creative freedom","Alignment with personal values","Low political friction","Ability to work independently"],"career_domains":["Writing","Counselling","UX Writing","Brand Strategy","Social Work","Education","Non-profit","Art Direction","Content Creation","Coaching"],"decision_making":"Values-based and intuition-led. Seek alignment between choice and deep personal meaning. Can struggle with decisions that require pure pragmatism.","leadership_style":"Serve and support rather than direct. Lead through example and authenticity. Inspire through personal integrity.","growth_edges":["Tolerating imperfect environments long enough to create change","Assertiveness","Converting ideals into practical plans"]},

"ENFJ": {"type":"ENFJ","name":"The Protagonist","work_style":"People-focused leader who energises teams and drives collaboration. Natural facilitator and developer of human potential. Work best when helping others grow while advancing a meaningful goal.","strengths":["People development","Inspirational communication","Team cohesion","Social awareness"],"energy_drains":["Work that ignores human impact","Prolonged conflict","Working in isolation","Environments that suppress individual expression"],"environment_needs":["People interaction","Meaningful goal","Recognition of contributions","Collaborative culture"],"career_domains":["People & Culture","Executive Coaching","Education","Non-profit Leadership","Healthcare Management","Marketing","Facilitation","Change Management"],"decision_making":"Weigh both data and human impact. Good at building consensus. Can over-prioritise team harmony at the expense of hard decisions.","leadership_style":"Develop people actively. Lead through inspiration and genuine care. Build strong loyalty. Need to balance people focus with business requirements.","growth_edges":["Making hard decisions that disappoint some","Prioritising own needs","Avoiding over-extension from helping too many people"]},

"ENFP": {"type":"ENFP","name":"The Campaigner","work_style":"Energetic, idea-driven, and people-inspiring. Excel at the creative and conceptual phase of work. Generate enthusiasm and connection. Need variety and autonomy to stay engaged. Struggle with routine and bureaucracy.","strengths":["Creative thinking","Building genuine connection","Inspiring action","Adaptability"],"energy_drains":["Rigid structure","Repetitive tasks","Bureaucratic process","Working without human connection"],"environment_needs":["Creative latitude","People interaction","Fast-moving environment","Permission to explore ideas"],"career_domains":["Marketing","Entrepreneurship","Coaching","Product Management","Journalism","Brand Strategy","Community Building","Event Production","Training & Development"],"decision_making":"Intuitive and enthusiastic. Make decisions based on gut and values, but can be swayed by social input. Benefit from structured decision frameworks.","leadership_style":"Lead through energy, vision, and genuine enthusiasm for people. Excel at culture-building. Need operational partners for execution discipline.","growth_edges":["Follow-through","Saying no to exciting opportunities","Tolerating the 'boring' implementation phase"]},

"ISTJ": {"type":"ISTJ","name":"The Logistician","work_style":"Reliable, methodical, and standards-driven. Bring order to complex systems. Work best with clear expectations, defined processes, and measurable outcomes. Deliver consistently, quietly, and with precision.","strengths":["Reliability","Process excellence","Attention to detail","Risk management"],"energy_drains":["Constant change without rationale","Ambiguous expectations","Having to repeat work due to others' lack of process","Chaotic environments"],"environment_needs":["Clear structure","Stable expectations","Recognition of consistent output","Quality-focused culture"],"career_domains":["Accounting","Operations Management","Project Management","Compliance","Engineering","Law","Finance","Supply Chain","Healthcare Administration"],"decision_making":"Evidence-based and methodical. Thoroughly evaluate before deciding. Cautious about deviation from what has worked before.","leadership_style":"Lead through example and consistency. High standards, clear expectations, fair evaluation. Prefer managing by process over inspiration.","growth_edges":["Adapting to necessary change","Considering novel approaches","Communicating concerns proactively rather than absorbing problems"]},

"ISFJ": {"type":"ISFJ","name":"The Defender","work_style":"Service-oriented, careful, and relationship-aware. Quietly reliable and deeply committed to people they care for. Work best in environments where their consistency and care are valued. Often underestimate their own impact.","strengths":["Reliability","Attention to others' needs","Institutional memory","Diplomatic communication"],"energy_drains":["Conflict and confrontation","Ungrateful environments","Lack of structure","Being asked to change established systems without clear reason"],"environment_needs":["Stable and supportive culture","Clear role expectations","Genuine team appreciation","Service-oriented mission"],"career_domains":["Healthcare","Social Work","Education","Human Resources","Office Management","Customer Success","Non-profit","Counselling"],"decision_making":"Cautious and considerate of impact on others. Prefer consensus and harmony. Can delay decisions to avoid conflict — benefit from explicit decision deadlines.","leadership_style":"Supportive and behind-the-scenes. Lead through service and quiet consistency. Build strong personal loyalty.","growth_edges":["Advocating for own needs","Setting limits without guilt","Prioritising strategic over operational"]},

"ESTJ": {"type":"ESTJ","name":"The Executive","work_style":"Organised, directive, and results-driven. Natural at running processes and organisations. Bring clear structure to complex environments. Direct communicators who value efficiency, accountability, and hierarchy.","strengths":["Operational leadership","Process implementation","Clear communication","Team accountability"],"energy_drains":["Lack of structure","Underperforming team members","Unclear decision authority","Values conflicts"],"environment_needs":["Clear hierarchy","Performance-oriented culture","Decision authority","Structured processes"],"career_domains":["Operations Management","General Management","Military","Law","Business Administration","Financial Planning","Corporate Training","Logistics"],"decision_making":"Decisively apply proven methods. Value precedent and established process. Can be resistant to unproven approaches — need evidence before pivoting.","leadership_style":"Direct, structured, and accountable. Set clear expectations and hold team to them. Value loyalty and consistent performance.","growth_edges":["Openness to unproven methods","Listening before directing","Adapting to different communication styles"]},

"ESFJ": {"type":"ESFJ","name":"The Consul","work_style":"People-oriented organisers who maintain group harmony while driving outcomes. Excel at coordination, communication, and making people feel valued. Motivated by visible positive impact on others.","strengths":["Relationship management","Coordination","Team culture","Operational communication"],"energy_drains":["Conflict and disharmony","Being excluded from team decisions","Work without visible human impact","Criticism without recognition"],"environment_needs":["Collaborative and warm culture","Clear social role","Recognition","People-facing work"],"career_domains":["Human Resources","Hospitality Management","Healthcare","Education","Community Management","Sales","Event Management","Non-profit"],"decision_making":"Consider impact on people and team dynamics. Build consensus before deciding. May avoid decisions that create interpersonal tension.","leadership_style":"Nurturing and collaborative. Create strong team cohesion. Recognise individuals publicly. Can struggle with performance management.","growth_edges":["Making hard calls that upset team members","Self-prioritisation","Giving direct critical feedback"]},

"ISTP": {"type":"ISTP","name":"The Virtuoso","work_style":"Practical problem-solver who excels with tools, systems, and real-world challenges. Thrive in hands-on, technical, and immediate environments. Efficient and precise, with strong spatial and mechanical intuition.","strengths":["Technical mastery","Crisis problem-solving","Efficient execution","Objectivity"],"energy_drains":["Abstract theorising without application","Long meetings","Emotional volatility","Over-structured environments"],"environment_needs":["Technical challenge","Autonomy","Real-world application","Results-focused culture"],"career_domains":["Engineering","IT","Skilled Trades","Military","Finance (Trading)","Forensics","Product Development","Data Analysis","Motorsport"],"decision_making":"Fast, pragmatic, and data-driven. Decide based on what works, not what should theoretically work. Comfortable with uncertainty if they can experiment their way through it.","leadership_style":"Lead by doing. Set technical standard. Prefer small teams with high competence. Minimal management overhead.","growth_edges":["Long-term planning","Communicating technical insight to non-technical stakeholders","Emotional dimension of team dynamics"]},

"ISFP": {"type":"ISFP","name":"The Adventurer","work_style":"Aesthetic-driven, present-focused, and values-aligned. Work best when craft, beauty, or personal expression is involved. Quiet but with strong opinions about what's right. Need freedom and flexibility.","strengths":["Aesthetic sensitivity","Authentic expression","Present-moment awareness","Empathic precision"],"energy_drains":["Bureaucratic restriction","Values conflicts","Long-range abstract planning","Highly competitive environments"],"environment_needs":["Creative freedom","Values alignment","Flexibility","Low political friction"],"career_domains":["Graphic Design","Fashion","Photography","Healthcare (Nursing)","Interior Design","Fine Art","UX/UI Design","Music","Crafts","Social Services"],"decision_making":"Trust personal values and aesthetic sense. Often make excellent decisions intuitively. Benefit from explicit exploration of practical implications.","leadership_style":"Lead through example and individual support. Create space for authentic expression. Uncomfortable with formal authority.","growth_edges":["Long-term career strategy","Asserting needs openly","Converting craft excellence into career capital"]},

"ESTP": {"type":"ESTP","name":"The Entrepreneur","work_style":"Action-oriented, opportunistic, and adaptable. Read environments rapidly and respond effectively. Excel under pressure and in fast-moving environments. Prefer doing over planning, results over process.","strengths":["Rapid situational assessment","Persuasion","Risk appetite","Crisis execution"],"energy_drains":["Abstract theory without application","Slow-moving environments","Over-planning","Bureaucracy"],"environment_needs":["High-energy environment","Results orientation","Autonomy","Real-world stakes"],"career_domains":["Sales","Entrepreneurship","Real Estate","Trading","Emergency Services","Hospitality","Sports","Marketing","Business Development"],"decision_making":"Fast, instinctive, and action-biased. Risk-tolerant and comfortable pivoting quickly. Benefit from pause-and-verify practice before large commitments.","leadership_style":"Lead from the front. High energy, charismatic, and direct. Inspire through action. Need to develop patience with careful thinkers on the team.","growth_edges":["Long-term thinking","Following established process","Active listening without interrupting"]},

"ESFP": {"type":"ESFP","name":"The Entertainer","work_style":"Social, energetic, and experience-driven. Bring life to teams and events. Work best in dynamic, people-facing environments where their warmth and spontaneity are assets. Not suited to solitary, analytical work.","strengths":["Social connection","Energy management","Improvisation","Positive environment creation"],"energy_drains":["Solitary analytical work","Rigid routine","Detailed planning","Abstract strategy"],"environment_needs":["Social interaction","Variety","Visible immediate impact","Supportive culture"],"career_domains":["Entertainment","Hospitality","Event Management","Sales","Healthcare (Frontline)","Teaching","Retail Management","Tourism","Coaching"],"decision_making":"In-the-moment and people-aware. Trust their read of social dynamics. Benefit from explicit long-term planning support.","leadership_style":"Lead through enthusiasm and genuine warmth. Build high morale. Need strong operational structure around them.","growth_edges":["Long-term planning","Following through on commitments","Analytical decision-making"]},
}

# ─── HD TYPES ────────────────────────────────────────────────────────────────
HD_TYPES = {
"Generator": {"type":"Generator","strategy":"Wait to Respond","energy":"Sustainable and consistent when engaged with genuinely exciting work. The workhorse of the world — 37% of the population.","work_approach":"Build mastery through sustained engagement with the right work. Do not initiate blindly — wait for something to respond to (an offer, an opportunity, a question). When the gut says yes, commit fully and build deep expertise over time.","career_advice":"Mastery compounds. Stay with work that lights you up rather than chasing novelty. The right role feels like it pulls you in, not like you're pushing upstream. Follow genuine excitement, not obligation.","burnout_signal":"Frustration. Trying to initiate things before the right moment, or staying in work that no longer excites, leads to chronic frustration and depletion.","strengths":["Sustainable energy when engaged","Natural mastery builder","Reliable and consistent","Magnetic life-force energy"],"pitfall":"Saying yes to things that don't genuinely excite them, or initiating without authentic response signal."},

"Manifesting_Generator": {"type":"Manifesting Generator","strategy":"Wait to Respond, then Inform before acting","energy":"High-volume, multi-track, and fast. Can do multiple things simultaneously that a Generator cannot. Often finish tasks faster than expected.","work_approach":"Multi-passionate and efficiency-driven. Need multiple streams of work simultaneously. Skip steps that seem unnecessary — often correctly. Inform people of what you're doing before doing it to reduce resistance.","career_advice":"Don't try to do one thing at a time — you're built for multi-track work. The skipping-steps tendency is a feature, not a flaw. Find roles or build portfolios that honour your breadth and speed.","burnout_signal":"Frustration AND anger. Frustration from initiating without response; anger from not informing others and meeting resistance.","strengths":["High capacity for diverse work","Speed and efficiency","Multi-track execution","Adaptive energy"],"pitfall":"Abandoning projects before they're complete because the initial excitement has passed."},

"Projector": {"type":"Projector","strategy":"Wait for the Invitation","energy":"Non-energy type. Cannot sustain energy the way Generators do. Need to manage output carefully and rest regularly. 20% of the population; designed to guide rather than produce.","work_approach":"Natural advisor and guide. See systems and people clearly. Most effective when invited to share insight. Excellent at directing the work of others — not designed for sustained manual or repetitive output.","career_advice":"Position yourself as the expert others invite in. Build a reputation and wait for the right recognition. Do not work harder to prove yourself — work more strategically and let your insight speak.","burnout_signal":"Bitterness. Working without recognition or invitation, or trying to match Generator energy, leads to exhaustion and resentment.","strengths":["Systems awareness","Insight and guidance","Efficiency through directing","Deep perceptiveness"],"pitfall":"Over-working to match Generator output, accepting invitations from the wrong people, sharing insights before invited."},

"Manifestor": {"type":"Manifestor","strategy":"Inform before acting","energy":"Initiating energy that is non-sustainable. Designed to start things and hand off to others. The only type designed to initiate without waiting. 9% of the population.","work_approach":"Initiate, inform, and move on. Need autonomy and independence above all else. Not designed to sustain projects long-term — their impact is in catalysing movement. Informing others before acting dramatically reduces resistance.","career_advice":"Find roles where initiation is valued and autonomy is protected. Entrepreneurship, creative direction, and catalytic leadership roles suit Manifestors. Build teams to handle execution.","burnout_signal":"Anger. From being controlled, micromanaged, or having to ask permission for every action.","strengths":["Initiating movement","Independent action","Catalytic impact","Creative direction"],"pitfall":"Not informing others before acting, leading to resistance and conflict. Staying too long in execution phases."},

"Reflector": {"type":"Reflector","strategy":"Wait a lunar cycle (28 days) before major decisions","energy":"Completely open design that samples the energy of environments and people around them. Rare — 1% of the population. Deeply sensitive to environmental quality.","work_approach":"Act as a barometer of collective health. Excel at evaluation, assessment, and creating environments where others can thrive. Need to be very selective about environment and the people around them — they amplify everything.","career_advice":"Environment is everything. Prioritise working in places and with people who are healthy and aligned. Do not rush major career decisions — use the full lunar cycle. Roles in evaluation, community building, and quality assessment suit Reflectors.","burnout_signal":"Disappointment. From living or working in unhealthy environments, or from making major decisions too quickly.","strengths":["Environmental sensitivity","Community evaluation","Impartiality","Wisdom from sampling many perspectives"],"pitfall":"Absorbing others' unhealthy energy, making major decisions too quickly, staying in wrong environments."},
}

# ─── HD AUTHORITIES ───────────────────────────────────────────────────────────
HD_AUTHORITIES = {
"Sacral": {"authority":"Sacral","description":"The most primal and instinctive authority. Exclusive to Generators and Manifesting Generators.","decision_style":"Gut-level, immediate response. A literal 'uh-huh' (yes) or 'uh-uh' (no) that arises in the body before the mind engages. Works best in real-time, responsive situations.","time_to_decide":"Immediate. Sacral responses are in-the-moment. If you have to think about it, it's no longer sacral.","career_application":"Trust the gut response when evaluating job offers, projects, and collaborations. If your body doesn't light up with an 'uh-huh', it's probably not right. Avoid overriding the sacral with mental justification.","common_mistake":"Overriding the gut response with mental reasoning ('but it pays well / looks good on the resume / is what I should want')."},

"Emotional_Solar_Plexus": {"authority":"Emotional / Solar Plexus","description":"Emotional clarity over time. The most common authority. Affects Generators, Manifesting Generators, Manifestors, and some Projectors.","decision_style":"Never in the now. Need to ride the full emotional wave (high to low and back) before clarity emerges. True yes feels consistently good across multiple days and moods.","time_to_decide":"Multiple days to weeks for important decisions. Minor decisions can be faster but should still avoid the emotional peak or trough.","career_application":"Do not accept job offers on the spot. Sleep on major career decisions. If it still feels right when you're neither excited nor down, it's probably correct. Use waiting time to gather information rather than to overthink.","common_mistake":"Deciding at the emotional peak (over-excitement) or trough (despair). Both distort the true signal."},

"Splenic": {"authority":"Splenic","description":"The oldest decision-making system — survival instinct. Spontaneous, in-the-moment knowing. Exclusive to Projectors, Manifestors, and some Generators.","decision_style":"Quiet, immediate knowing in the body. Unlike sacral, it doesn't repeat itself — speaks once. Often mistaken for intuition but is actually a direct survival intelligence.","time_to_decide":"Immediate. The splenic hit is always in the present moment and does not repeat.","career_application":"Learn to recognise the subtle body signal that says yes or no. Trust first impressions in work environments, about people, and about opportunities. The intelligence is in the immediate response, not reflection.","common_mistake":"Waiting for the splenic signal to repeat or strengthen. It won't — if you missed it, you missed it."},

"Ego_Heart": {"authority":"Ego / Heart","description":"Will-based authority. Rare. Affects some Manifestors and Projectors.","decision_style":"Decisions made from what you genuinely want and are willing to commit to. The question is 'what do I want?' and 'am I willing to do what it takes?' — not 'should I' or 'is this a good idea'.","time_to_decide":"Can be immediate. The clarity comes from checking in with desire and will, not with logic or emotion.","career_application":"Only commit to what you genuinely want and have the will to sustain. Don't make promises you're not willing to keep. Your word is a measure of your will — only speak it when you mean it completely.","common_mistake":"Making decisions based on what seems logical or what others want, rather than what you genuinely desire."},

"Self-Projected": {"authority":"Self-Projected","description":"Exclusive to Projectors with an open emotional centre and defined G centre. Talk things through to find clarity.","decision_style":"Clarity comes through speaking your truth out loud to a trusted listener. Not seeking their advice — just being heard. Your own voice reveals what you actually want.","time_to_decide":"After speaking through the decision with someone you trust. Listen to yourself, not to them.","career_application":"Cultivate a small circle of trusted listeners for major career decisions. Talk through options out loud. Pay attention to what comes out of your mouth rather than what's in your head.","common_mistake":"Asking for opinions and following advice rather than listening to your own voice emerging in the conversation."},

"Mental_Environmental": {"authority":"Mental / Environmental","description":"Exclusive to Projectors and Reflectors with no defined centres below the throat. Environment and people are the authority.","decision_style":"Move through different environments and speak with different trusted people. Notice how your body feels in each context. The right decision becomes clear through environmental comparison rather than analysis.","time_to_decide":"After sampling multiple perspectives and environments. Not a quick authority.","career_application":"Before accepting a role, visit the physical environment if possible. Notice how your body responds. Speak with people in different roles about the opportunity. Your environment literally affects your wellbeing.","common_mistake":"Trying to make decisions in isolation or through mental analysis alone."},

"Lunar": {"authority":"Lunar","description":"Exclusive to Reflectors. The only authority that follows a full 28-day moon cycle.","decision_style":"Wait the full lunar cycle (28 days) before making major decisions. During this time, speak with different trusted people and sample different environments. By the end of the cycle, clarity emerges.","time_to_decide":"28 days for major decisions. Use the time to sample perspectives, not to analyse repeatedly.","career_application":"Never accept a major career offer immediately. Request a reasonable time to consider. Use the 28 days to sit with the opportunity, visit environments, and speak with trusted advisors. Clarity will emerge naturally.","common_mistake":"Rushing major decisions, or making them in a single conversation or environment."},
}

# ─── HD PROFILES ─────────────────────────────────────────────────────────────
HD_PROFILES = {
"1_3": {"profile":"1/3","name":"Investigator / Martyr","life_theme":"Build a solid foundation of knowledge, then learn through experimentation and 'failure'.","work_pattern":"Need to thoroughly research before feeling confident. Trial-and-error is the natural learning mode — every 'mistake' builds real expertise. The martyr line means setbacks are part of the path, not signals to stop.","career_approach":"Build deep foundational knowledge first. Then experiment practically. Don't stay in roles or relationships that aren't working — the 3 line learns by discovering what doesn't work. Multiple career phases are normal.","strengths":["Deep foundational expertise","Resilience through trial","Practical wisdom","Willingness to experiment"],"growth_edge":"Releasing self-blame for 'failures' — they are the data, not the verdict."},

"1_4": {"profile":"1/4","name":"Investigator / Opportunist","life_theme":"Build thorough knowledge, then share it through stable networks of trusted relationships.","work_pattern":"Research deeply before acting. Opportunities come through existing relationships, not cold outreach. Career moves are best made through people who already trust and know you.","career_approach":"Build your network intentionally and maintain it genuinely. Your next role will likely come from within your existing circle. Invest deeply in both expertise and trusted relationships.","strengths":["Deep knowledge base","Network leverage","Foundation plus community","Trusted expertise"],"growth_edge":"Not becoming so research-dependent that action is delayed indefinitely."},

"2_4": {"profile":"2/4","name":"Hermit / Opportunist","life_theme":"Develop your natural genius in solitude, then share it through your established network.","work_pattern":"Need significant alone time to develop natural talents. Resist being pulled out of their natural development too early. When ready, opportunities come through existing relationships.","career_approach":"Protect time for solitary development of your natural gifts. When you're called out by others who see your talent, consider it seriously — that's your invitation. Career moves via your network, not applications.","strengths":["Natural talent development","Relationship depth","Organic talent recognition","Authentic contribution"],"growth_edge":"Recognising when solitude has shifted from development to hiding."},

"2_5": {"profile":"2/5","name":"Hermit / Heretic","life_theme":"Develop natural genius in private, then be called upon as the practical problem-solver.","work_pattern":"People project their hopes and solutions onto the 2/5. This creates a reputation that precedes them. Need significant solitude but will be called out repeatedly to solve others' problems.","career_approach":"Develop expertise privately. Be selective about which calls you answer — you cannot help everyone. Build a reputation for practical problem-solving. Manage the projection that will come with visibility.","strengths":["Natural talent","Practical problem-solving","Magnetic reputation","Wide reach when called out"],"growth_edge":"Managing the weight of others' projections without taking them personally."},

"3_5": {"profile":"3/5","name":"Martyr / Heretic","life_theme":"Learn through experimentation and trial, then become the practical problem-solver for others.","work_pattern":"Build wisdom through lived experience — the 3 line tries, adjusts, and tries again. This produces deep practical knowledge. The 5 line means others will project their needs onto you and seek your solutions.","career_approach":"Embrace career experimentation. Multiple roles and industries across a career is the design, not a failure. Each 'failure' produces real wisdom. When you become known as someone who has done the work, the right invitations come.","strengths":["Experiential wisdom","Resilience","Practical solution-finding","Natural magnetism"],"growth_edge":"Releasing shame about past 'failures' — they are the raw material of your expertise."},

"3_6": {"profile":"3/6","name":"Martyr / Role Model","life_theme":"Three-phase life: trial (0-30), roof (30-50), role model (50+). Embody wisdom accumulated across all phases.","work_pattern":"First half of career marked by experimentation and discovery of what works. From mid-career, become a trusted observer and synthesiser. Later, become the role model whose lived wisdom inspires others.","career_approach":"Accept that your early career is meant to be exploratory. Don't rush to 'find your thing' — you're building material for later wisdom. After 30-35, start transitioning from experimenter to synthesiser.","strengths":["Multi-phase wisdom","Authentic role modelling","Lived credibility","Long-arc development"],"growth_edge":"Trusting the process during the 'roof' phase — observation feels passive but is essential."},

"4_6": {"profile":"4/6","name":"Opportunist / Role Model","life_theme":"Build a strong community of influence, then become a role model through embodied living.","work_pattern":"Career built entirely through existing network and close relationships. Not designed for cold outreach or mass visibility. Influence grows through trusted circles over time.","career_approach":"Invest deeply in your community. Your opportunities will come from people who know and trust you. By mid-career, start developing the qualities of the role model you're designed to become.","strengths":["Deep network","Community influence","Trusted relationships","Long-term credibility"],"growth_edge":"Accepting that influence through a small network is valid — you don't need mass reach."},

"4_1": {"profile":"4/1","name":"Opportunist / Investigator","life_theme":"Build expertise and a strong network simultaneously. Security through both knowledge and community.","work_pattern":"Opportunities come through existing relationships but also require solid foundational knowledge to back them up. Network and expertise reinforce each other throughout the career.","career_approach":"Develop genuine expertise while simultaneously nurturing your professional relationships. When network opportunities arise, your knowledge base makes you credible.","strengths":["Network leverage","Foundational expertise","Community trust","Knowledge-backed influence"],"growth_edge":"Ensuring expertise development doesn't become a reason to delay network-based action."},

"5_1": {"profile":"5/1","name":"Heretic / Investigator","life_theme":"Build a thorough knowledge base, then be called upon as the practical problem-solver for collective challenges.","work_pattern":"Others project solutions and expertise onto 5/1s even before they've proven themselves. Need solid knowledge base to back up the reputation they're given. Called to solve collective (not just individual) problems.","career_approach":"Build expertise carefully — you'll be asked to apply it publicly. Be selective about which problems you agree to solve. Your reputation is a powerful tool that must be protected through real knowledge.","strengths":["Deep expertise","Wide reach","Collective problem-solving","Powerful reputation"],"growth_edge":"Managing the projection of others and maintaining the knowledge base that justifies it."},

"5_2": {"profile":"5/2","name":"Heretic / Hermit","life_theme":"Develop natural genius privately, then be called out to solve problems for many.","work_pattern":"The most reclusive profile that carries the most public expectation. Need significant alone time to develop naturally. When called out, have significant reach and impact. Cannot sustain constant visibility.","career_approach":"Protect solitude fiercely — it's where your natural talent develops. When called into public roles, make a genuine contribution and then return to private development. Do not stay in the spotlight longer than necessary.","strengths":["Natural genius","Practical impact","Wide influence when called out","Genuine contribution"],"growth_edge":"Accepting the tension between the need for solitude and the call to public contribution."},

"6_2": {"profile":"6/2","name":"Role Model / Hermit","life_theme":"Three-phase development toward becoming a trusted role model, needing significant private development time.","work_pattern":"Strong need for solitude to develop natural gifts. The role model quality emerges gradually — by mid-career, others begin to look to the 6/2 as someone who has 'figured it out'. Embodied living is the teaching.","career_approach":"Honour the need for private development without apology. Opportunities come through recognition of natural talent. By mid-career, start consciously developing the values and lifestyle you want to model for others.","strengths":["Natural talent","Embodied wisdom","Genuine role modelling","Quiet authority"],"growth_edge":"Not retreating into solitude so completely that the invitation to contribute never comes."},

"6_3": {"profile":"6/3","name":"Role Model / Martyr","life_theme":"Learn through experimentation in the first half of life, then become a role model for authentic living.","work_pattern":"Early career marked by experimentation and honest mistakes. This builds real credibility. From mid-life, the 6/3 embodies what they've learned and naturally becomes an inspiration to others who see their authentic journey.","career_approach":"Allow early career experimentation without self-judgment. Each trial teaches something real. From 35+, begin consciously living and expressing the values you've discovered. Your authentic story is your authority.","strengths":["Experiential wisdom","Authentic credibility","Role model through lived experience","Practical resilience"],"growth_edge":"Trusting that the experimental phase was necessary and not a waste of time."},
}

def write_knowledge(folder, name, data):
    path = BASE / folder / f"{name}.json"
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  ✓ {folder}/{name}.json")

print("Generating knowledge files...")

for code, data in MBTI.items():
    write_knowledge("mbti", code, data)

for name, data in HD_TYPES.items():
    write_knowledge("hd_types", name, data)

for name, data in HD_AUTHORITIES.items():
    write_knowledge("hd_authorities", name, data)

for name, data in HD_PROFILES.items():
    write_knowledge("hd_profiles", name, data)

total = len(MBTI) + len(HD_TYPES) + len(HD_AUTHORITIES) + len(HD_PROFILES)
print(f"\nDone — {total} knowledge files generated.")
